#!/usr/bin/sh
# run application with java env >= 11

PDFSAM_EXECUTABLE="/usr/share/java/pdfsam/bin/pdfsam.sh"

run_pdfsam() {
    exec "${PDFSAM_EXECUTABLE}"
    exit 0
}

export JAVA_HOME=/usr/lib/jvm/jre-11
export JDK_HOME=/usr/lib/jvm/jre-11
export JRE_HOME=/usr/lib/jvm/jre-11

run_pdfsam
